theme: jekyll-theme-cayman
title: "IoT news Blog"
description: "B2B Home Energy Management Solutions"
baseurl: "/iotnews"
url: "https://owonsmart.github.io"
permalink: /:year/:month/:day/:title.html
plugins:
  - jekyll-seo-tag
plugins:
  - jekyll-sitemap
logo: /assets/image/ow-logo.png

# Open Graph 默认设置
defaults:
  - scope:
      path: ""
    values:
      image: /assets/image/og-logo.png
